import { Post } from './api';

export const mockPosts: Post[] = [
  {
    id: '1',
    title: 'Unlocking Business Efficiency with SaaS Solutions',
    content: 'Software as a Service (SaaS) has revolutionized the way businesses operate, offering scalable, cost-effective solutions that can be accessed from anywhere in the world. In this comprehensive guide, we explore how SaaS platforms are transforming industries by providing flexible, subscription-based services that eliminate the need for expensive hardware and software installations.',
    excerpt: 'A short intro to how SaaS improves operations and productivity with examples and best practices.',
    author: 'Jennifer Taylor',
    date: '2023-10-15',
    category: 'Business',
    imageUrl: 'https://picsum.photos/seed/saas-business/1200/360.jpg',
    readTime: 3,
  },
  {
    id: '2',
    title: 'Revolutionizing industries through SaaS implementation',
    content: 'The implementation of SaaS solutions across various industries has led to unprecedented levels of efficiency and innovation. From healthcare to finance, education to retail, businesses are leveraging cloud-based technologies to streamline operations, enhance customer experiences, and drive growth.',
    excerpt: 'Explore how SaaS implementation is driving innovation across diverse industry sectors.',
    author: 'Michael Chen',
    date: '2023-10-10',
    category: 'Technology',
    imageUrl: 'https://picsum.photos/seed/saas-tech/1200/360.jpg',
    readTime: 5,
  },
  {
    id: '3',
    title: 'Synergizing SaaS and UX design for elevating digital experiences',
    content: 'The intersection of SaaS platforms and user experience design represents a critical frontier in digital product development. This article examines how thoughtful UX design can significantly enhance SaaS adoption rates, user satisfaction, and overall business success.',
    excerpt: 'Learn how UX design principles can enhance SaaS platforms and improve user satisfaction.',
    author: 'Sarah Williams',
    date: '2023-10-05',
    category: 'Design',
    imageUrl: 'https://picsum.photos/seed/saas-ux/1200/360.jpg',
    readTime: 4,
  },
  {
    id: '4',
    title: 'Navigating SaaS waters with intuitive UI and UX',
    content: 'As SaaS applications become increasingly complex, the importance of intuitive user interfaces and experiences cannot be overstated. This piece delves into best practices for creating SaaS interfaces that users find both powerful and easy to navigate.',
    excerpt: 'Discover best practices for creating intuitive interfaces in complex SaaS applications.',
    author: 'David Rodriguez',
    date: '2023-09-28',
    category: 'Design',
    imageUrl: 'https://picsum.photos/seed/saas-ui/1200/360.jpg',
    readTime: 6,
  },
  {
    id: '5',
    title: 'Sculpting SaaS success - the art of UI and UX design',
    content: 'Successful SaaS products are built on a foundation of exceptional UI and UX design. This article explores the art and science of creating SaaS interfaces that not only look beautiful but also provide seamless, efficient user experiences.',
    excerpt: 'Explore the art and science behind successful UI/UX design for SaaS products.',
    author: 'Emily Johnson',
    date: '2023-09-20',
    category: 'Design',
    imageUrl: 'https://picsum.photos/seed/saas-design/1200/360.jpg',
    readTime: 7,
  },
  {
    id: '6',
    title: 'Transforming SaaS platforms - a UI/UX design odyssey',
    content: 'The journey of transforming a SaaS platform through strategic UI/UX design is both challenging and rewarding. This case study examines the complete redesign process of a major SaaS platform, highlighting key decisions and their impact on user engagement and business metrics.',
    excerpt: 'Follow a complete SaaS platform redesign journey and its impact on user engagement.',
    author: 'Robert Kim',
    date: '2023-09-15',
    category: 'Case Study',
    imageUrl: 'https://picsum.photos/seed/saas-case/1200/360.jpg',
    readTime: 8,
  },
  {
    id: '7',
    title: 'Mastering UI Elements: A Practical Guide for Designers',
    content: 'UI elements form the building blocks of any digital interface. This comprehensive guide covers everything from buttons and forms to navigation menus and data visualizations, providing practical advice for creating effective, accessible UI components.',
    excerpt: 'A comprehensive guide to creating effective UI elements for modern digital interfaces.',
    author: 'Jennifer Taylor',
    date: '2023-09-10',
    category: 'Design',
    imageUrl: 'https://picsum.photos/seed/ui-elements/1200/360.jpg',
    readTime: 12,
  },
  {
    id: '8',
    title: 'Crafting Seamless Experiences: The Art of Intuitive UI Design',
    content: 'Intuitive UI design is both an art and a science. This article explores the principles and techniques that guide designers in creating interfaces that feel natural to users, reducing learning curves and improving overall satisfaction.',
    excerpt: 'Explore the principles behind creating intuitive user interfaces that feel natural to users.',
    author: 'Alex Morgan',
    date: '2023-09-05',
    category: 'Design',
    imageUrl: 'https://picsum.photos/seed/intuitive-ui/1200/360.jpg',
    readTime: 8,
  },
  {
    id: '9',
    title: 'Beyond Aesthetics: The Power of Emotional UX Design',
    content: 'While aesthetics are important, the most impactful designs connect with users on an emotional level. This piece delves into the psychology of emotional design and how it can be leveraged to create more meaningful, memorable user experiences.',
    excerpt: 'Discover how emotional design principles can create more meaningful user experiences.',
    author: 'Ryan A.',
    date: '2023-08-28',
    category: 'Psychology',
    imageUrl: 'https://picsum.photos/seed/emotional-ux/1200/360.jpg',
    readTime: 7,
  }
];